<?php
/**
* Implements hook_block_info().
*/

function _copyright_it_block_info() { 
  $blocks = array(); 
  $blocks['copyright_it'] = array(
    'info' => t('Copyright it by Your website '),
    'weight' => '-50',
  );
  return $blocks; 
}

function _copyright_it_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'copyright_it':
      $block['title'] = '';
      $block['content'] = copyright_it_copyright_date();
    break;
  }
  return $block;
}


function copyright_it_copyright_date() { 
	$site_name = variable_get('site_name');
	return '<span></span><br><span><center>Copyright &copy; ' . date("Y") .', ' . $site_name . '</center></span> <br><span></span>' ; 
}