<?php

/**
 * @file
 * This file inserts the extra layouts into Display Suite.
 */

/**
 * Implements hook_ds_layout_info().
 */
function ds_extra_layouts_ds_layout_info() {

  // Get the path to the module.
  $path = drupal_get_path('module', 'ds_extra_layouts');

  $layouts = array();

  $layouts['two_column_33_66'] = array(
    'label' => t('Two Column 33/66'),
    'path' => $path . '/layouts/two_column_33_66',
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['two_column_66_33'] = array(
    'label' => t('Two Column 66/33'),
    'path' => $path . '/layouts/two_column_66_33',
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['two_column_stacked_33_66'] = array(
    'label' => t('Two Column Stacked 33/66'),
    'path' => $path . '/layouts/two_column_stacked_33_66',
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['two_column_stacked_66_33'] = array(
    'label' => t('Two Column Stacked 66/33'),
    'path' => $path . '/layouts/two_column_stacked_66_33',
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['fluid_two_column_33_66'] = array(
    'label' => t('Fluid Two Column 33/66'),
    'path' => $path . '/layouts/fluid_two_column_33_66',
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['fluid_two_column_66_33'] = array(
    'label' => t('Fluid Two Column 66/33'),
    'path' => $path . '/layouts/fluid_two_column_66_33',
    'regions' => array(
      'left' => t('Left'),
      'right' => t('Right'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['fluid_two_column_stacked_33_66'] = array(
    'label' => t('Fluid Two Column Stacked 33/66'),
    'path' => $path . '/layouts/fluid_two_column_stacked_33_66',
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['fluid_two_column_stacked_66_33'] = array(
    'label' => t('Fluid Two Column Stacked 66/33'),
    'path' => $path . '/layouts/fluid_two_column_stacked_66_33',
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['two_column_bricks'] = array(
    'label' => t('Two Column Bricks'),
    'path' => $path . '/layouts/two_column_bricks',
    'regions' => array(
      'header' => t('Header'),
      'above_left' => t('Above Left'),
      'above_right' => t('Above Right'),
      'middle' => t('Middle'),
      'below_left' => t('Below Left'),
      'below_right' => t('Below Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['three_column_nested_left'] = array(
    'label' => t('Three Column Nested Left'),
    'path' => $path . '/layouts/three_column_nested_left',
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'middle' => t('Middle'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['three_column_nested_right'] = array(
    'label' => t('Three Column Nested Right'),
    'path' => $path . '/layouts/three_column_nested_right',
    'regions' => array(
      'header' => t('Header'),
      'left' => t('Left'),
      'middle' => t('Middle'),
      'right' => t('Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['three_column_bricks'] = array(
    'label' => t('Three Column Bricks'),
    'path' => $path . '/layouts/three_column_bricks',
    'regions' => array(
      'header' => t('Header'),
      'above_left' => t('Above Left'),
      'above_middle' => t('Above Middle'),
      'above_right' => t('Above Right'),
      'middle' => t('Middle'),
      'below_left' => t('Below Left'),
      'below_middle' => t('Below Middle'),
      'below_right' => t('Below Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['four_column_bricks'] = array(
    'label' => t('Four Column Bricks'),
    'path' => $path . '/layouts/four_column_bricks',
    'regions' => array(
      'header' => t('Header'),
      'above_first' => t('Above First'),
      'above_second' => t('Above Second'),
      'above_third' => t('Above Third'),
      'above_fourth' => t('Above Fourth'),
      'middle' => t('Middle'),
      'below_first' => t('Below First'),
      'below_second' => t('Below Second'),
      'below_third' => t('Below Third'),
      'below_fourth' => t('Below Fourth'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['two_column_double_bricks'] = array(
    'label' => t('Two Column Double Bricks'),
    'path' => $path . '/layouts/two_column_double_bricks',
    'regions' => array(
      'header' => t('Header'),
      'above_left' => t('Above Left'),
      'above_right' => t('Above Right'),
      'above_brick' => t('Above Brick'),
      'middle_left' => t('Middle Left'),
      'middle_right' => t('Middle Right'),
      'below_brick' => t('Below Brick'),
      'below_left' => t('Below Left'),
      'below_right' => t('Below Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['four_column_stacked'] = array(
    'label' => t('Four Column Stacked'),
    'path' => $path . '/layouts/four_column_stacked',
    'regions' => array(
      'header' => t('Header'),
      'first' => t('First'),
      'second' => t('Second'),
      'third' => t('Third'),
      'fourth' => t('Fourth'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['three_column_double_bricks'] = array(
    'label' => t('Three Column Double Bricks'),
    'path' => $path . '/layouts/three_column_double_bricks',
    'regions' => array(
      'header' => t('Header'),
      'above_left' => t('Above Left'),
      'above_middle' => t('Above Middle'),
      'above_right' => t('Above Right'),
      'above_brick' => t('Above Brick'),
      'middle_left' => t('Middle Left'),
      'middle_middle' => t('Middle Middle'),
      'middle_right' => t('Middle Right'),
      'below_brick' => t('Below Brick'),
      'below_left' => t('Below Left'),
      'below_middle' => t('Below Middle'),
      'below_right' => t('Below Right'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  $layouts['four_column_double_bricks'] = array(
    'label' => t('Four Column Double Bricks'),
    'path' => $path . '/layouts/four_column_double_bricks',
    'regions' => array(
      'header' => t('Header'),
      'above_first' => t('Above First'),
      'above_second' => t('Above Second'),
      'above_third' => t('Above Third'),
      'above_fourth' => t('Above Fourth'),
      'above_brick' => t('Above Brick'),
      'middle_first' => t('Middle First'),
      'middle_second' => t('Middle Second'),
      'middle_third' => t('Middle Third'),
      'middle_fourth' => t('Middle Fourth'),
      'below_brick' => t('Below Brick'),
      'below_first' => t('Below First'),
      'below_second' => t('Below Second'),
      'below_third' => t('Below Third'),
      'below_fourth' => t('Below Fourth'),
      'footer' => t('Footer'),
    ),
    'css' => TRUE,
    'image' => TRUE,
  );
  return $layouts;
}
