language: php

php:
  - 7.0
  - nightly

notifications:
  email: false
  irc: false

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_ARGS='--show-diff' LDFLAGS="-lgcov" CFLAGS="-Wall -coverage -O0" EXTRA_LDFLAGS="-precious-files-regex .libs/oauth.gcno"

#Compile
before_script:
    - phpize
    - ./configure
    - make

# Run PHPs run-tests.php
script:
  - make test
  - gcov --object-directory .libs *.c
  - bash <(curl -s https://codecov.io/bash)
